---
abstract: 'Furl based S3 client library.'
author:
  - 'Tomohiro Ikebe <ikebe {at} shebang.jp>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Furl-S3
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Class::Accessor::Lite: 0
  Digest::HMAC_SHA1: 0
  File::Type: 0
  Furl: 0.38
  HTTP::Date: 0
  MIME::Base64: 0
  Params::Validate: 0
  URI::Escape: 0
  XML::LibXML: 0
  XML::LibXML::XPathContext: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
